# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Phaemie Ng"
logo: "logo.png"
repository: "phaemie/phaemie.github.io"
email: contact@phaemie.com
description: The personal site of Phaemie Ng
baseurl: "" # the subpath of your site, e.g. /blog
prod_host: phaemie.com
url: "https://phaemie.com" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: phaemie.com
linkedin_username: phaemieng
# twitter_username: phaemie

# Build settings
markdown: kramdown
theme: minima
gems:
  - webrick
  - jekyll-svg-plugin
  - jekyll-email-protect
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
collections:
  case_studies:
    output: true
    permalink: /case-study/:title
defaults:
  -
    scope:
      path: ""
      type: case_studies
    values:
      layout: "case_study"